### ISSUE TITLE
Assets/Plugins/Unity.TransformChangesDebugger.API/Runtime/Patches/TransformPatches.cs(349,118): error CS0165: Use of unassigned local variable 'jumpLabelAfterSetter'

### ISSUE THREAD

**Issue by pixelpax** [handzlikchris/Unity.TransformChangesDebugger.API#1]
Steps to reproduce: 
All I did to install was drag the github repo into my Assets/Plugin directory. This error seems to prevent compile

**Comment by pixelpax** [comment]
Using Unity 2021.3.6f1

**Comment by handzlikchris** [comment]
Hi @pixelpax.

I think there was a minor change with Unity version and now unassigned variables give compile time error instead of warning.

I've pushed a change to fix that, it needs to be assigned on that line with new()
